require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'bin/bundle'
    - 'templates/**/*'
    - 'config/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/AmbiguousOperator:
  Exclude:
    - 'exe/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - '*.gemspec'

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'features/step_definitions/**/*'