name: Publish gem to GitHub Public Registry

on:
  release:
    types:
      - published
jobs:

  push:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.5

    steps:
      - uses: actions/checkout@v1
      - name: Publish to GPR
        run: |
          gem install keycutter --no-document
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.GPR_AUTH_TOKEN}}
          OWNER: tk-hamaguchi
