name: Ruby

on: [push]

jobs:

  build_test_and_push:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.5

    steps:
      - uses: actions/checkout@v1
      - run: gem install bundler --no-document
      - run: bundle install --jobs 4 --retry 3 --deployment
      - run: bundle exec rubocop -c .rubocop.yml -D
      - run: bundle exec cucumber features/ -fpretty
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: bundle exec rspec spec/ -fd
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish to GPR
        run: |
          gem install keycutter --no-document
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.GPR_AUTH_TOKEN}}
          OWNER: tk-hamaguchi
